# Generated by Django 6.0 on 2025-12-28 11:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название игры')),
                ('description', models.TextField(verbose_name='Описание игры')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='game_logos/', verbose_name='Логотип')),
                ('release_date', models.DateField(verbose_name='Дата выхода')),
                ('developer', models.CharField(max_length=100, verbose_name='Разработчик')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='Издатель')),
                ('genre', models.CharField(choices=[('RPG', 'Ролевые игры'), ('FPS', 'Шутеры'), ('STR', 'Стратегии'), ('ADV', 'Приключения'), ('SIM', 'Симуляторы'), ('SPT', 'Спортивные'), ('IND', 'Инди'), ('MMO', 'ММО'), ('MOB', 'MOBA')], max_length=3, verbose_name='Жанр')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('avg_rating', models.FloatField(default=0.0, verbose_name='Средний рейтинг')),
            ],
            options={
                'verbose_name': 'Игра',
                'verbose_name_plural': 'Игры',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Оценка (1-10)')),
                ('content', models.TextField(verbose_name='Текст отзыва')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Авор')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.game', verbose_name='Игра')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['-created_date'],
                'unique_together': {('game', 'author')},
            },
        ),
    ]
